User update info
malashonock/rslang pull request #100
Opened 2022-09-01 11:36 UTC by stanlys

Перебил форму

Можно изменить email и password
Можно удалить пользователя

[![Screenshot-8.jpg](https://i.postimg.cc/MHKX4Pwd/Screenshot-8.jpg)](https://postimg.cc/R6yMJTNH)

2022-09-06 09:59 UTC, malashonock requested changes
1. По-прежнему после обычного sign-in срабатывает редирект на update profile
2. После обновления, скажем, пароля форма не выводит вообще никакие сообщения - не ок для UX, юзеру нужно сказать, что данные успешно обновлены - или не обновлены

2022-09-06 16:05 UTC, malashonock requested changes
- [ ] По-прежнему после обычного sign-in срабатывает редирект на update profile
 - [x] После обновления, скажем, пароля форма не выводит вообще никакие сообщения - не ок для UX, юзеру нужно сказать, что данные успешно обновлены - или не обновлены

2022-09-06 16:05 UTC, malashonock commented on src/features/auth/UserHomePage.tsx
> +  const [isServerError, serIsServerError] = useState<boolean>(false);
`set` только (и в следующей строке)

2022-09-06 17:23 UTC, stanlys commented on src/features/auth/UserHomePage.tsx
> +  const [isServerError, serIsServerError] = useState<boolean>(false);
день сегодня сложный выдался, ошибаюсь на ровном месте. Прошу прощения.

2022-09-06 23:50 UTC, malashonock commented
По странному редиректу на update форму: наверно, это происходит из-за navigate(-1), т.к. до этого как раз и была открыта update форма
Попробуй залезть в эту предыдущую запись, куда navigate делается, и повесить на нее условие, что если это какая-то signin/signup/update форма - то на главную, иначе на -1 как по умолчанию

2022-09-07 06:19 UTC, stanlys commented
> По странному редиректу на update форму: наверно, это происходит из-за navigate(-1), т.к. до этого как раз и была открыта update форма Попробуй залезть в эту предыдущую запись, куда navigate делается, и повесить на нее условие, что если это какая-то signin/signup/update форма - то на главную, иначе на -1 как по умолчанию

пока не могу определить с какой страницы был осуществен переход.. разбираюсь

2022-09-07 08:47 UTC, stanlys commented
нашел решение, но оно как мне кажется странное
const oldPage: string = location.state?.from || '/';
Протестируй у себя

2022-09-07 17:16 UTC, malashonock approved these changes
Добавил коммит от себя

2022-09-07 21:46 UTC, merged